Repository doomemacs/themes, pull requests merged in 2022-11, with the labels that each got.

#755 docs: fix #customize link in project readme
  README.md
Labels: is:docs

#757 feat(base): add disk-usage faces
  doom-themes-base.el
Labels: is:faces, theme:base

#756 feat(base): add mm-uu-extract face
  doom-themes-base.el
Labels: is:faces, re:emacs
