Repository doomemacs/themes, pull requests merged in 2025-06, with the labels that each got.

#832 tweak(base): Inherit `flycheck-posframe-info-face` from `success`
  doom-themes-base.el
Labels: is:tweak, theme:base

#853 docs: follow use-package recommendations
  README.md
Labels: is:docs

#863 Added actual link to Dracula theme
  README.md
Labels: theme:dracula, is:docs
